package com.global.smartplug;
import android.app.*; import android.os.*; import android.content.*; import android.content.pm.PackageManager; import android.net.wifi.WifiManager; import android.provider.Settings; import android.graphics.Color; import android.widget.*;
public class MainActivity extends Activity {
 Switch master,o1,o2,o3,o4; TextView masterState,wifiStatus; static final int REQ=10;
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);master=findViewById(R.id.master);o1=findViewById(R.id.o1);o2=findViewById(R.id.o2);o3=findViewById(R.id.o3);o4=findViewById(R.id.o4);masterState=findViewById(R.id.masterState);wifiStatus=findViewById(R.id.wifiStatus);
 master.setOnCheckedChangeListener((v,on)->{o1.setChecked(on);o2.setChecked(on);o3.setChecked(on);o4.setChecked(on);masterState.setText(on?"الحالة: تشغيل":"الحالة: إيقاف");masterState.setTextColor(Color.parseColor(on?"#63E63D":"#9AAAB4"));});
 findViewById(R.id.addDevice).setOnClickListener(v->showAddDevice()); findViewById(R.id.wifiSetup).setOnClickListener(v->showWifiSetup()); updateWifiStatus();}
 void updateWifiStatus(){WifiManager w=(WifiManager)getApplicationContext().getSystemService(WIFI_SERVICE);wifiStatus.setText(w!=null&&w.isWifiEnabled()?"Wi-Fi: مفعّل":"Wi-Fi: غير مفعّل");}
 void showWifiSetup(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.ACCESS_FINE_LOCATION")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.ACCESS_FINE_LOCATION"},REQ);return;}startActivity(new Intent(Settings.ACTION_WIFI_SETTINGS));Toast.makeText(this,"اتصل بشبكة الجهاز GlobalSmartPlug أو MTTL-W01 ثم ارجع للتطبيق",Toast.LENGTH_LONG).show();}
 void showAddDevice(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(30,10,30,10);EditText n=new EditText(this);n.setHint("اسم الجهاز");box.addView(n);EditText m=new EditText(this);m.setHint("MAC Address");box.addView(m);EditText s=new EditText(this);s.setHint("Serial Number");box.addView(s);new AlertDialog.Builder(this).setTitle("إضافة جهاز").setView(box).setPositiveButton("حفظ",(d,w)->Toast.makeText(this,"تم حفظ الجهاز محليًا",Toast.LENGTH_SHORT).show()).setNegativeButton("إلغاء",null).show();}
}
